### PR TITLE
fix 'random' exception handler

### LINKED ISSUE #97: [PE-D][Tester B] Give a random recipe feature program crushed
After I have deleted all the recipe in the list, and tried to generate a random recipe, the program crushed

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Sherlock-YH/ped#7

### PR DESCRIPTION
**Pull request by JuneNita**
closes #97

### CODE REVIEW

**Comment by gurmankalkat** [comment]
LGTM

File: src/main/java/seedu/meal360/Ui.java [hunk 1]
```diff
@@ -138,4 +138,23 @@ public void printUserIngredients(IngredientList userIngredients) {
...
+        }
+    }
+
+    public void printSuccessfullyAddTag(String tag) {
+        printMessage("You have successfully added the recipe(s) to \"" + tag + "\" tag.");
+    }
+
+    public void printSuccessfullyRemoveTag(String tag) {
+        printMessage("You have successfully removed the recipe(s) from \"" + tag + "\" tag.");
+    }
```
Comment (TopGun2001) [inline src/main/java/seedu/meal360/Ui.java:159]: Very neat code.
